### ISSUE TITLE
Is Lammps running in parallel?

### ISSUE THREAD

**Issue by pzarabadip** [LMMorgan/PopOff#8]
[context]
To me it seems that we are calling the `Lammps` in its serial mode.

For instance, in `lammps_data.py` and in the `initiate_lammps` function, we have:
```
lmp = lammps() 
lmp.command('units metal')
```
This initiated `lammps()` class would call `Lammps` in serial according to:

https://github.com/lammps/lammps/blob/652864ed5c4331a05c38247eabe8021a5d3588ef/python/lammps/core.py#L70
https://github.com/lammps/lammps/blob/652864ed5c4331a05c38247eabe8021a5d3588ef/python/lammps/core.py#L83

As we do not pass any argument to the `name`.

[solution]
Possibly we can have an extra key-value in parameter which would switch on/off running in parallel. `mpi` needs to be assigned to `name` as:
```
lmp = lammps(name='mpi')
```
We may do a sanity check at initialization state to check for `liblammps_mpi.so`.

**Comment by mjclarke94** [comment]
Alternatively, given the calculation being performed by lammps is relatively cheap, would a multiprocessing pool potentially be a better use of the resources available?

**Comment by pzarabadip** [comment]
That might be a case @mjclarke94.
As core-shell calculations are taking so long time to finish, I'm trying to find the bottle-neck.  

I'm trying to test even if that simple argument assignment would call lammps in parallel. 
Documentation of lammp-python seems a bit outdated. They mention a code snippet like below:
```
from mpi4py import MPI
from lammps import lammps
lmp = lammps()
lmp.file("in.lj")
me = MPI.COMM_WORLD.Get_rank()
nprocs = MPI.COMM_WORLD.Get_size()
print("Proc %d out of %d procs has" % (me,nprocs),lmp)
MPI.Finalize()
```
while I do not see what would be the reason of having `name` argument in the class then?

**Comment by mjclarke94** [comment]
CProfile would show whether or not the flag was changing how it was running in the backend?

**Comment by pzarabadip** [comment]
Worth checking this package:
https://github.com/pyiron/pylammpsmpi

**Comment by LMMorgan** [comment]
The optimiser is already running a multiprocessing pool. It fires of jobs for "possible potential values", runs them for each structure in the set in parallel. So each initialisation of lammps should be handled separately. The slowdown is due to requiring a full minimisation of the shells (when fitting core shell) in addition to the single step calculation, for ever structure and instance. The lammps run itself may not be parallelised according to your observations. I shall test making this change as determine if we gain any speed up.

**Comment by bjmorgan** [comment]
multiprocessing will only help if the optimisation algorithm can take advantage of running LAMMPS calculations in parallel. So I think it ends up running single core calculations for each structure, which is not terrible, but unlikely to be the optimal way to divide up resources. Ideally each LAMMPs calculation could be run in parallel, but implementing this is more complicated.

**Comment by LMMorgan** [comment]
I have run local tests which should that including MPI doesn't increase the speed of a single structure run. I shall keep the change as there are no negative effects, and will conduct further testing with a larger number of cores and a larger training set. The benefit might scale.
